language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk-3-dev libcairo2-dev 
  - git clone --quiet git://github.com/diagrams/monoid-extras.git diagrams/monoid-extras
  - git clone --quiet git://github.com/diagrams/dual-tree.git diagrams/dual-tree
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/core
  - git clone --quiet git://github.com/diagrams/diagrams-lib.git diagrams/lib
  - git clone --quiet git://github.com/diagrams/diagrams-cairo.git diagrams/cairo
  - git clone --quiet git://github.com/diagrams/diagrams-contrib.git diagrams/contrib
  - git clone --quiet git://github.com/diagrams/docutils.git diagrams/docutils
  - cd diagrams
  - cabal install gtk2hs-buildtools shake
  - cabal install monoid-extras/ dual-tree/ core/ lib/ cairo/ contrib/ docutils/
  - cd ..

script: "ghc --make Shake && ./Shake"